#ifndef Constant_h__
#define Constant_h__

const BYTE INSTCNT = 32;
const BYTE MAX_BONE_MATRICES = 64;
const BYTE MAX_NAME = 128;
const BYTE NODELAYANICNT = 3;

const WORD WINCX = 1280;
const WORD WINCY = 720;

const WORD MAPCX = 513;
const WORD MAPCZ = 513;
const WORD MAPITV = 2;

enum RESOURCETYPE	{ RESOURCE_STATIC, RESOURCE_LOGIN, RESOURCE_STAGE, RESOURCE_END };
enum MESHNUM		{ MESHNUM_PLAYER ,MESHNUM_END};
enum ANIPLAYER		{ PLAYER_IDLE, PLAYER_ATTACK, PLAYER_MOVE , PLAYER_DIE};

#endif // Constant_h__